### ISSUE TITLE
can we use it in flutter app directly show qr code ?

### ISSUE THREAD

**Issue by mahendrajungthapa** [iamnabink/fonepay_flutter#2]
as it doesnt show qr code fonepay in mobile is there any way we can show qr code also in our flutter app?

**Comment by iamnabink** [comment]
Hi @mahendrajungthapa, thanks for the issue. For QR, it's their (fonePay's) web view hai, so I think it's responsive, and seems like in small devices they hide it. Other than the small devices, it works on iPad/tabs. But I will look further enhancement if something can be done in V2.
